baseurl = "https://www.gelliottmorris.com/"
languageCode = "en-us"
title = "G. Elliott Morris"
subtitle = "My personal website"
author = "G. Elliott Morris"
description = ""
canonifyURLs = true
enableEmoji = true
googleAnalytics = "UA-76096508-1" # delete this to disable google analytics
rssLimit = 10
ignoreFiles = ["\\.Rmd$", "\\.Rmarkdown$", "_files$", "_cache$"]
theme = "pristine"

[params]
    portrait = "img/elliott.png"

[[menu.main]]
    name = "Home"
    url = "/"
    weight = 1

[[params.social]]
    title = "Email"
    url = "mailto:john@doe.com"
[[params.social]]
    title = "Follow @johndoe"
    url = "https://twitter.com/johndoe"
[[params.social]]
    title = "Github"
    url = "https://github.com/johndoe"
[[params.social]]
    title = "Facebook"
    url = "https://facebook.com/johndoe"
