baseURL = "https://www.gelliottmorris.com/"
languageCode = "en-us"
title = "G. Elliott Morris"
canonifyURLs = true
enableEmoji = true

theme = "pristine"

[params]
    portrait = "img/elliott.png"

[[params.social]]
    title = ""
    icon = "fa fa-envelope fa-lg"
    url = "mailto:elliott@thecrosstab.com"
[[params.social]]
    title = ""
    icon = "fa fa-twitter fa-lg"
    url = "https://twitter.com/gelliottmorris"
[[params.social]]
    title = ""
    icon = "fa fa-github fa-lg"
    url = "https://github.com/elliottmorris"   
[[params.social]]
    title = "Blog"
    icon = ""
    url = "https://www.thecrosstab.com"

    