baseURL = "https://www.gelliottmorris.com/"
languageCode = "en-us"
title = "G. Elliott Morris"
canonifyURLs = true
enableEmoji = true
googleAnalytics = "UA-XXXXXX-1"

theme = "pristine"

[params]
    portrait = "img/elliott.png"

[[menu.main]]
  name = "Home"
  url = "/"
  weight = 1

[[menu.main]]
  name = "Blog"
  url = "https://www.thecrosstab.com"
  weight = 2


[[params.social]]
    title = "Email"
    url = "mailto:elliott@thecrosstab.com"
[[params.social]]
    title = "Follow @gelliottmorris"
    url = "https://twitter.com/gelliottmorris"
[[params.social]]
    title = "Github"
    url = "https://github.com/elliottmorris"
