baseURL = "https://www.gelliottmorris.com/"
languageCode = "en-us"
title = "G. Elliott Morris"
canonifyURLs = true
enableEmoji = true

theme = "pristine"

[params]
    portrait = "img/elliott.png"

[permalinks]
    page = "/:slug/"
    post = "/:year/:month/:day/:slug/"
    
[[menu.main]]
    url = "/writing/"
    name = "Writing"
    weight = 1

[[menu.main]]
    url = "/code/"
    name = "Code"
    weight = 2

[[menu.main]]
    url = "/post/"
    name = "Blog"
    weight = 3

[[params.social]]
    title = ""
    icon = "fa fa-twitter fa-lg"
    url = "https://twitter.com/gelliottmorris"

[[params.social]]
    title = ""
    icon = "fa fa-github fa-lg"
    url = "https://github.com/elliottmorris"   

[[params.social]]
    title = ""
    icon = "fa fa-envelope fa-lg"
    url = "mailto:elliott@thecrosstab.com"

    